In [7]:
import numpy as np


In [3]:
x = np.arange(1,10).reshape(3,3)
print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [7]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [8]:
# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)



W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [9]:
# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)


Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [10]:
# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)


v =  [10 11 12 13 14]


In [12]:
# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)


q =  [ 2  7 12 17]


In [13]:
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)


R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


In [43]:
algo = np.arange(1,21).reshape(5,4)
print(algo)
print(algo.shape)
print()
am = algo[algo % 2]
print(am)
print()
print(am.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
(5, 4)

[[[5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]

 [[5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]

 [[5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]

 [[5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]

 [[5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]]

(5, 4, 4)


In [31]:
x = np.ones((4,4))
print(x)
print()
y = np.arange(1,5)
print(y)
print()
print(np.multiply(x,y))
print()

x1 = np.arange(0,19,2).reshape(5,2)
print(x1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[1 2 3 4]

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
